### ISSUE TITLE
A feature to share these photos or posts to different other friends through various applications or through the same app .

### ISSUE THREAD

**Issue by Abhiram-Gullapalli** [NS007-dev/InstDOGram#3]
I felt it would be great if this single feature was added along with your  list of features.

**Comment by CodingSpecies** [comment]
@gullapalli9482 thank you for adding to my list of features! I will add this to my list, and by who suggested it! Thank you!

**Comment by CodingSpecies** [comment]
Commited: https://github.com/CodingSpecies/InstDOGram/commit/2cacf073aa9db7aa8eed964107b136570df3fbea

**Comment by CodingSpecies** [comment]
When I can, I will try to work on this Thank you @gullapalli9482
